name: BIST Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"  # Her saat başı. */30 yaparsan 30dk'da bir çalışır

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Repoyu cek
        uses: actions/checkout@v4

      - name: Node kur
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Paketleri yukle
        run: npm ci

      - name: Botu calistir
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: node bot.js